import { Inter } from "next/font/google";
import React from "react";
const inter = Inter({ subsets: ["latin"] });
import { NextAuthProvider } from "./providers";
import "./globals.css";
import { AppToast } from "@/packages";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          {children}
          <AppToast />
        </NextAuthProvider>
      </body>
    </html>
  );
}
